### ISSUE TITLE
Add VRF to Routing Instance Model

### ISSUE THREAD

**Issue by Jawny** [nautobot/nautobot-app-bgp-models#243]
### Environment
* Nautobot version: 2.0.3
* nautobot-bgp-models version:  2.3.1

### Proposed Functionality
Add VRF to routing instance model and enforce routing instances be unique with (AS,VRF) pairs.

### Use Case
Allows users to query a routing instance and get back VRF. Also since a VRF is a separate virtual routing instance on a device it make sense to have a mapping between Routing Instance <> VRF. The default routing instance can represent the default VRF and new ones created can be associated with some other VRF. This allows multiple peerings to be created with the same AS but with different VRFs.

**Comment by zsblevins** [comment]
This is for Cumulus routers, we have certain peerings that need to be established in multiple VRFs. The configuration appears as follows:

```
...
    vrf:
      default:                             # VRF name, default here
        router:
          bgp:
            address-family:
              ipv4-unicast:
                aggregate-route:
                  X.X.X.X/26:
                    route-map: AGGREGATE-ROUTE
                    summary-only: on
                enable: on
                redistribute:
                  connected:
                    enable: on
                    route-map: REDISTRIBUTE-CONNECTED
            enable: on
            neighbor:
              X.X.X.X:
                peer-group: OOB-SWITCH
                description: oobsw1
                type: numbered
                remote-as: 4266008000
              ...
            path-selection:
              multipath:
                aspath-ignore: on
            peer-group:
              ...
              OOB-SWITCH:
                address-family:
                  ipv4-unicast:
                    community-advertise: {}
                    policy:
                      inbound:
                        route-map: RM-OOBSW-IN
                      outbound:
                        route-map: RM-OOBSW-OUT
                    soft-reconfiguration: on
                  l2vpn-evpn:
                    enable: off
                bfd:
                  detect-multiplier: 3
                  enable: on
                  min-rx-interval: 300
                  min-tx-interval: 300
                password: <REDACTED>
              ...
      TO-TAN:  # VRF name, TO-TAN
        evpn:
          enable: on
          vni:
            '1000': {}
          vlan: 1000
        router:
          bgp:
            rd: X.X.X.X:1000
            address-family:
              ipv4-unicast:
                enable: on
                redistribute:
                  connected:
                    enable: on
                    route-map: REDISTRIBUTE-CONNECTED
                route-export:
                  to-evpn:
                    enable: on
            enable: on
            neighbor:
              X.X.X.X:                    # Distinct IP/interface from the peering in default
                peer-group: OOB-SWITCH
                description: oobsw1
                type: numbered
                remote-as: 4266008000
            ...
            peer-group:
              OOB-SWITCH:
                address-family:
                  ipv4-unicast:
                    community-advertise: {}
                    policy:
                      inbound:
                        route-map: RM-OOBSW-IN
                      outbound:
                        route-map: RM-OOBSW-OUT
                    soft-reconfiguration: on
                  l2vpn-evpn:
                    enable: off
                bfd:
                  detect-multiplier: 3
                  enable: on
                  min-rx-interval: 300
                  min-tx-interval: 300
                password: <REDACTED>
              ...
            route-export:
              to-evpn:
                route-target:
                  4266000000:1000: {}
            route-import:
              from-evpn:
                route-target:
                  4266000000:1000: {}
```

So we need to model peerings between this router and oobsw1 in the above example, the default VRF peering is established on the physical interface, and the TO-TAN peering is established on a sub-interface between the 2 in VLAN 1000. This is for EVPN.
